# Generated by Django 5.0.6 on 2026-05-31 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('gemini', 'Gemini'), ('azure', 'Azure OpenAI'), ('mistral', 'Mistral'), ('groq', 'Groq'), ('ollama', 'Ollama')], max_length=20)),
                ('encrypted_api_key', models.BinaryField(blank=True, null=True)),
                ('api_key_last_4', models.CharField(blank=True, max_length=4)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('azure_region', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(max_length=255)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.PositiveIntegerField(default=2048)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_status', models.CharField(choices=[('untested', 'Untested'), ('ok', 'OK'), ('failed', 'Failed')], default='untested', max_length=10)),
                ('last_test_error', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_provider_configs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_config', to='workspaces.workspace')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
