# Generated by Django 5.0.6 on 2026-06-02 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0002_lowercase_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspaceinvitation',
            name='invited_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
