# Generated by Django 5.0.6 on 2026-06-02 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('workspaces', '0003_invited_at_mutable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('token_input_count', models.PositiveIntegerField(default=0)),
                ('token_output_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_workspa_23e376_idx',
            old_name='chat_conver_workspa_idx',
        ),
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_last_me_f07e7c_idx',
            old_name='chat_conver_last_me_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_convers_3154fc_idx',
            old_name='chat_messag_convers_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='chat_messag_workspa_359981_idx',
            old_name='chat_messag_workspa_idx',
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='workspaces.workspace'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['workspace', 'date'], name='chat_usager_workspa_533081_idx'),
        ),
        migrations.AddIndex(
            model_name='usagerecord',
            index=models.Index(fields=['user', 'date'], name='chat_usager_user_id_fedd6c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagerecord',
            unique_together={('workspace', 'user', 'date')},
        ),
    ]
